// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb0xRDQ3bvrneSXwV5U6lzRnQdIoYnsdo',
    appId: '1:352349213826:web:85fcf807b34e0dfb87109b',
    messagingSenderId: '352349213826',
    projectId: 'ipopi-8d919',
    authDomain: 'ipopi-8d919.firebaseapp.com',
    storageBucket: 'ipopi-8d919.firebasestorage.app',
    measurementId: 'G-SDY7MY0EZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoVi5vLxzpvS_mwEZfLX_YDVLZLRyAHj8',
    appId: '1:352349213826:android:8a1aae8067ae0b1a87109b',
    messagingSenderId: '352349213826',
    projectId: 'ipopi-8d919',
    storageBucket: 'ipopi-8d919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANbcQQ1XeMwZFBL7QUjYwwhRigT19DVpw',
    appId: '1:352349213826:ios:e8417a140ccd8f1f87109b',
    messagingSenderId: '352349213826',
    projectId: 'ipopi-8d919',
    storageBucket: 'ipopi-8d919.firebasestorage.app',
    iosBundleId: 'com.example.ipopi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANbcQQ1XeMwZFBL7QUjYwwhRigT19DVpw',
    appId: '1:352349213826:ios:e8417a140ccd8f1f87109b',
    messagingSenderId: '352349213826',
    projectId: 'ipopi-8d919',
    storageBucket: 'ipopi-8d919.firebasestorage.app',
    iosBundleId: 'com.example.ipopi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb0xRDQ3bvrneSXwV5U6lzRnQdIoYnsdo',
    appId: '1:352349213826:web:15d66b259e16ac8d87109b',
    messagingSenderId: '352349213826',
    projectId: 'ipopi-8d919',
    authDomain: 'ipopi-8d919.firebaseapp.com',
    storageBucket: 'ipopi-8d919.firebasestorage.app',
    measurementId: 'G-PT8BEDXBSJ',
  );
}
